### ISSUE TITLE
Health bar for LivingSprites + Mana bar for player

### ISSUE THREAD

**Issue by albertopoljak** [Den4200/game-jam-2020#15]
Some enemies (preferably bosses) should have health bar.

Should it be similar to damage indicator and be above them, or should we make big health bar that will be full screen width at the top of screen is to be discussed.

Another thing we can add is a mana bar for the player for shooting / abillities.

**Assets we can use** - https://adwitr.itch.io/pixel-health-bar-asset-pack-2

**Comment by F4zii** [comment]
We can also make a mana-bar for shooting / abillities, a nice asset is https://adwitr.itch.io/pixel-health-bar-asset-pack-2

**Comment by F4zii** [comment]
**So, heres some ideas for an implemention:**

1. First Idea:
    - We have an abstract class for healthbar, assets include the border of the health bar and a piece of the filling - can be 10% of it for 10 lives.

    - We will add / remove filling parts when needed.

2. Second one:
    - We will draw a rectangle below the bar border, easier, but will remove the shadows from the fill

**Comment by F4zii** [comment]
Done. I might reopen this or open another issue for a similar topic.
