### ISSUE TITLE
Potions and abillities

### ISSUE THREAD

**Issue by F4zii** [Den4200/game-jam-2020#26]
Implement potions and abilities for each color.

**Comment by albertopoljak** [comment]
Started in branch power-abilities-feature
Implemented time slow for blue for now, planning to do floor stomp for red.

For potions, I guess they can be a way to reduce ability cooldown, or to temporally buff some stats.

**Comment by albertopoljak** [comment]
Abilities implemented, moving potions issue to separate issue.
