### ISSUE TITLE
Implement soundtrack

### ISSUE THREAD

**Issue by albertopoljak** [Den4200/game-jam-2020#43]
We already have soundtrack manager, make it play.

**Comment by albertopoljak** [comment]
Kinda done, but the soundtrack manager max_volume doesn't work.
Make it similar as to sound manager so you can set volume and use global setting for default soundtrack volume

**Comment by albertopoljak** [comment]
And it HAS TO work with slomode aka it has to support lower volume, othervise the whole slowmo effect isn't there.

**Comment by F4zii** [comment]
Done

**Comment by albertopoljak** [comment]
Beautiful <3
