### ISSUE TITLE
Card menu "cheat"

### ISSUE THREAD

**Issue by F4zii** [Den4200/game-jam-2020#8]
## Description
When the player is in trouble, he can just open the cards menu and relax, think about what he should do for a while, i think this is not optimal  and we should have some sort of uptime for the cards menu.

#### Alternatives for pausing
What we should probably do for pausing is a simple menu to pause the game, but the menu will hide or blur the game.

**Comment by Den4200** [comment]
This can be fixed by doing what other games do: slow down time while the player is hovering over the cards. I think that’s what we should do.

**Comment by F4zii** [comment]
Sounds good to me. applies a very nice effect also!

**Comment by albertopoljak** [comment]
Blur is not supported and would be hard to implement without hacks, so slowdown would be excellent effect.

Closing this in favor of #10
