### ISSUE TITLE
Player is being stuck in certain tiles

### ISSUE THREAD

**Issue by F4zii** [Den4200/game-jam-2020#9]
The player can't pass certain tiles and being glitchy.

**Comment by Den4200** [comment]
This is because path finding has not yet been implemented.

**Comment by F4zii** [comment]
Im talking about actual movement, you can't pass between certain tiles when you can pass between others. I will record and add an attachment later on.

**Comment by Den4200** [comment]
Yeah I know, you have to be exactly in the right position to be able to pass through 1 tile spaces. It’s because the movement we have right now isn’t actual path finding.

**Comment by Den4200** [comment]
Fixed. The wizard was a bit too big to fit in one tile spaces, so I manually set the hitbox. 3350527
